apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app2-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-app2
      version: blue
  template:
    metadata:
      labels:
        app: mi-app2
        version: blue
    spec:
      containers:
        - name: mi-app2
          image: norman404/eneroappnodes:<IMAGE_TAG>
          ports:
            - containerPort: 3000